volumes:
  mongodb_DB:
  mongodb_conf:

networks: 
  app:

services:
  mongo:
    image: mongo:8.0.9
    restart: unless-stopped
    volumes:
      - mongodb_DB:/data/db
      - mongodb_conf:/data/configdb
    networks: 
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PRODUCTION=1
    ports:
      - 5001:5001
    networks:
      - app

  worker:
    image: ghcr.io/tls-attacker/tlsanvil:v1.2.9
  #  image: tls-anvil
    restart: always
    networks:
      - app
    volumes:
      - ./output:/output/
    command: ["worker", "-controller", "app:5001", "-name", "Docker Compose bundeled Worker"]
