FROM node:24
RUN apt-get install gnupg curl
RUN curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
RUN echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
RUN apt-get update
RUN apt-get install -y mongodb-org zip

VOLUME /input
VOLUME /output

COPY backend /build/backend
WORKDIR /build/backend
RUN npm install
RUN npm run build

COPY frontend /build/frontend
RUN rm -r /build/frontend/src/lib
COPY backend/src/lib/* /build/frontend/src/lib/
WORKDIR /build/frontend
RUN npm install

COPY generate_static_report.sh /build
RUN chmod +x /build/generate_static_report.sh
WORKDIR /build
ENTRYPOINT ./generate_static_report.sh